### ISSUE TITLE
Where is the docs about keepTime parameters of tz() ?

### ISSUE THREAD

**Issue by purell** [moment/momentjs.com#595] opened 2019-09-06 15:11 UTC
Hi,

I looked for the best I could, but could not find any information about the `keepTime` parameter of the 

```js
moment.tz (..., keepTime)
               ¯¯¯¯¯¯¯¯¯¯
```

function.

I think I understand what the parameter is doing : 

> When the keepTime parameter is missing or false, the time is only interpreted to the specified timezone without changing the internal value. When the keepTime parameter is true, the internal time is adjusted so that the time is created at the local time of this timezone instead of transposing from gtm. 

Sorry It's poorly written but this is the best I can do. Maybe someone could explain it better ? Anyway, **a minimum of documentation on that would have been very helpful**.

Refs :
* https://github.com/moment/moment-timezone/blob/develop/moment-timezone.js#L562
* https://github.com/moment/momentjs.com/blob/master/docs/moment-timezone/01-using-timezones/03-converting-to-zone.md

**Comment by qfan** [comment] 2020-01-31 02:36
It's a bit confusing. Here's how I understand it:

If keepTime=true, we only set the time zone info, causing the actual moment to change, but the *face value* of the time is kept.

If keepTime=false, the time is converted to the given timezone, so the displayed date and time may change, but the result refers to the exact same moment before calling `tz`.

```
moment('2020-01-30T18:00:00-0800').tz('America/New_York').format()
"2020-01-30T21:00:00-05:00"
moment('2020-01-30T18:00:00-0800').tz('America/New_York', true).format()
"2020-01-30T18:00:00-05:00"
moment('2020-01-30T18:00:00-0800').tz('America/New_York', false).format()
"2020-01-30T21:00:00-05:00"
moment.version
"2.24.0"
```

**Comment by marwahaha** [comment] 2020-05-13 01:03
duplicate of #586

**Closed by marwahaha** 2020-05-13 01:03 UTC
