### ISSUE TITLE
Documentation: clarity required.

### ISSUE THREAD

**Issue by justinwyllie** [moment/momentjs.com#307] opened 2016-05-27 12:36 UTC
I raised this as a [Stackoverflow question](http://stackoverflow.com/questions/37463807/how-to-convert-a-local-datetime-to-utc-with-moment-js) and have correctly been directed here. 

The issue concerns creating a moment with a local datetime and then outputting this as UTC. This is the line of code:

moment(mylocaldatetime).utc().format()

What this actually does is create a moment using the given local time, puts moment into utc mode, and then formats it as UTC. For example; in a local time zone which is UTC + 1

moment('2016-05-23T16:10:04.630000').utc().format()
==> 2016-05-23T15:10:04Z

However the docs are (in my opinion) somewhat lacking in clarity. 

In the Parse/UTC section it says: 

"If you want to parse or display a moment in UTC, you can use moment.utc() instead of moment()"

This seems to imply that moment(datetime).utc() will treat the given datetime as if it were UTC. But this is not correct. It will treat it as a local datetime. It may then internally parse it as UTC but from a user's perspective this implies that moment will treat the given input as if it were UTC which, as I say, is not correct. 

In the following section parseZone this line also has the same issue:

"Moment normally interprets input times as local times (or UTC times if moment.utc() is used)"

I think in at least the first case it needs to be made clear that the input date is still considered as local. Something like:

"If you want to parse or display a moment in UTC, you can use moment.utc() instead of moment(). In this case moment will consider the input date as local time but will parse it internally in UTC mode"

**Comment by mj1856** [comment] 2016-05-27 14:22
There's a difference between `moment(input).utc()` and `moment.utc(input)`.  Both leave the moment in UTC mode, but the first parses in local mode.

There's also `moment.utc(input).local()`, which would parse in UTC and then switch to local mode.

Of course, a Loy of this depends on input.  If the input contains an offset then it doesn't really matter what mode you parse it in, only the mode you end up in.

Yes, some of this could be clearer.

**Comment by marwahaha** [comment] 2019-01-20 23:50
closing as duplicate of https://github.com/moment/momentjs.com/issues/307

**Closed by marwahaha** 2019-01-20 23:50 UTC
Labels: Up-For-Grabs
